<a href="https://colab.research.google.com/github/Srithan22/tekworks/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
!pip3 install numpy


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[[1,2,3],[3,4,5]],[[2,3,4],[7,8,9]]])
c=np.array(42)
d=np.array([1,2,3,4])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


2
3
0
1


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[[1,2,3],[3,4,5]],[[2,3,4],[7,8,9]]])
c=np.array(42)
d=np.array([1,2,3,4])
print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [3 4 5]]

 [[2 3 4]
  [7 8 9]]]
42
[1 2 3 4]


In [ ]:
import numpy as np
zeros = np.zeros((2,3))
print(zeros)


ones = np.ones((3,3))
print(ones)

random_array = np.random.rand(2,2)
print(random_array)

id= np.eye(3)
print(id)

range_array = np.arange(1,10,2)
print(range_array)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.95564877 0.59197513]
 [0.87513299 0.51738358]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("size:",arr.size)
print("data type:",arr.dtype)
print("itemsize:",arr.itemsize)
print("data:",arr.data)
print("Number of dimensions:",arr.ndim)

Shape: (2, 3)
size: 6
data type: int64
itemsize: 8
data: <memory at 0x7d73ff28d220>
Number of dimensions: 2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.

Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.


In [ ]:
import numpy as np
gh1 = np.array([22, 24, 23])
gh2 = np.array([25, 26, 24])

temp_data = np.array([gh1, gh2])

print(temp_data)

print("\nArray Properties:")
print("Shape:", temp_data.shape)
print("Size:", temp_data.size)
print("Data Type:", temp_data.dtype)
print("Number of Dimensions:", temp_data.ndim)

gh3 = np.array([21, 23, 22])
updated_temp_data = np.vstack([temp_data, gh3])

print("\n Updated Temperature Data:")
print(updated_temp_data)

sensor_error_flags = np.zeros((2, 3), dtype=int)
greenhouse_identity = np.identity(3, dtype=int)


print("\n Sensor Error Flags:")
print(sensor_error_flags)

print("\n Greenhouse Identity Matrix:")
print(greenhouse_identity)

[[22 24 23]
 [25 26 24]]

Array Properties:
Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2

 Updated Temperature Data:
[[22 24 23]
 [25 26 24]
 [21 23 22]]

 Sensor Error Flags:
[[0 0 0]
 [0 0 0]]

 Greenhouse Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,1])
print(arr[1,-1])
print(arr[0,-1])
print(arr[0:])

20
60
30
[[10 20 30]
 [40 50 60]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


In [ ]:
import numpy as np


shipments = np.array([
    [50, 60, 70, 65, 75, 80, 85],   # Apples
    [30, 35, 40, 45, 50, 55, 60],   # Oranges
    [90, 85, 88, 92, 95, 97, 99]    # Bananas
])

print("Weekly Fruit Shipments (Mon–Sun):")
print(shipments)

apples_wed = shipments[0, 2]
oranges_sun = shipments[1, 6]

print("\nIndexing Results:")
print("Apples shipped on Wednesday:", apples_wed)
print("Oranges shipped on Sunday:", oranges_sun)


weekday_shipments = shipments[:, 0:5]  # Mon–Fri
weekend_shipments = shipments[:, 5:7]  # Sat–Sun
apples_wed_to_sat = shipments[0, 2:6]  # Wed–Sat for Apples

print("\n Weekday Shipments (Mon–Fri):")
print(weekday_shipments)

print("\nWeekend Shipments (Sat & Sun):")
print(weekend_shipments)

print("\n Apples Shipments (Wed–Sat):")
print(apples_wed_to_sat)

print("\n Updating Saturday Apples shipment from 80 to 100")
shipments[0, 5] = 100

print("\nUpdated Shipments Data:")
print(shipments)

Weekly Fruit Shipments (Mon–Sun):
[[50 60 70 65 75 80 85]
 [30 35 40 45 50 55 60]
 [90 85 88 92 95 97 99]]

Indexing Results:
Apples shipped on Wednesday: 70
Oranges shipped on Sunday: 60

 Weekday Shipments (Mon–Fri):
[[50 60 70 65 75]
 [30 35 40 45 50]
 [90 85 88 92 95]]

Weekend Shipments (Sat & Sun):
[[80 85]
 [55 60]
 [97 99]]

 Apples Shipments (Wed–Sat):
[70 65 75 80]

 Updating Saturday Apples shipment from 80 to 100

Updated Shipments Data:
[[ 50  60  70  65  75 100  85]
 [ 30  35  40  45  50  55  60]
 [ 90  85  88  92  95  97  99]]



Arithmetic

In [ ]:

import numpy as np
a = np.array([1,2,3,4])
b= np.array([5,6,7,8])
print(a+b)#element wise
print(a*b)#elementwise multiplication
print(a*2)#scalar multiplication

#matrix operation
m1 =np.array([[1,2],[3,4]])
m2 =np.array([[5,6],[7,8]])
r=np.dot(m1,m2)
print(r)

[ 6  8 10 12]
[ 5 12 21 32]
[2 4 6 8]
[[19 22]
 [43 50]]


NumPy automatically applies operations across arrays of different shapes and sizes through a mechanism called broadcasting, which allows element-wise operations without the need for explicit looping.

In [ ]:
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


1. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.i

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Arithmetic Universal Functions
print("➤ Addition of x and y:\n", np.add(x, y))
print("➤ Subtraction of x and y:\n", np.subtract(x, y))
print("➤ Multiplication of x and y:\n", np.multiply(x, y))
print("➤ Division of x by y:\n", np.divide(x, y))
print("➤ Power x^y:\n", np.power(x, y))
print("➤ Modulus of x % y:\n", np.mod(x, y))

# Exponential and Log Universal Functions
print("\n➤ Exponential of x (e^x):\n", np.exp(x))
print("➤ Natural log of x (ln x):\n", np.log(x))
print("➤ Base-10 log of x:\n", np.log10(x))
print("➤ Base-2 log of x:\n", np.log2(x))
print("➤ Exponential minus 1 of x (e^x - 1):\n", np.expm1(x))

# Trigonometric Universal Functions
print("\n➤ Sine of x:\n", np.sin(x))
print("➤ Cosine of x:\n", np.cos(x))
print("➤ Tangent of x:\n", np.tan(x))

# For arcsin and arccos, clip x to [-1,1] to avoid warnings
x_clipped = np.clip(x, -1, 1)
print("➤ Arcsine of x (clipped):\n", np.arcsin(x_clipped))
print("➤ Arccosine of x (clipped):\n", np.arccos(x_clipped))
print("➤ Arctangent of x:\n", np.arctan(x))
print("➤ Convert x from radians to degrees:\n", np.degrees(x))
print("➤ Convert x from degrees to radians:\n", np.radians(x))

# Rounding Universal Functions
print("\n➤ Rounded values of x:\n", np.round(x))
print("➤ Floor values of x:\n", np.floor(x))
print("➤ Ceil values of x:\n", np.ceil(x))
print("➤ Truncated values of x:\n", np.trunc(x))

# Statistical Universal Functions
print("\n➤ Minimum value in x:\n", np.min(x))
print("➤ Maximum value in x:\n", np.max(x))
print("➤ Mean of x:\n", np.mean(x))
print("➤ Standard deviation of x:\n", np.std(x))
print("➤ Variance of x:\n", np.var(x))
print("➤ Sum of all elements in x:\n", np.sum(x))
print("➤ Product of all elements in x:\n", np.prod(x))

# Logical Universal Functions
print("\n➤ Logical AND of x and y:\n", np.logical_and(x, y))
print("➤ Logical OR of x and y:\n", np.logical_or(x, y))
print("➤ Logical NOT of x:\n", np.logical_not(x))
print("➤ Logical XOR of x and y:\n", np.logical_xor(x, y))

# Comparison Universal Functions
print("\n➤ x > y:\n", np.greater(x, y))
print("➤ x < y:\n", np.less(x, y))
print("➤ x == y:\n", np.equal(x, y))
print("➤ x != y:\n", np.not_equal(x, y))
print("➤ x >= y:\n", np.greater_equal(x, y))

# Bitwise Universal Functions
print("\n➤ Bitwise AND of x and y:\n", np.bitwise_and(x, y))
print("➤ Bitwise OR of x and y:\n", np.bitwise_or(x, y))
print("➤ Bitwise XOR of x and y:\n", np.bitwise_xor(x, y))
print("➤ Bitwise NOT of x:\n", np.invert(x))

➤ Addition of x and y:
 [[ 6  8]
 [10 12]]
➤ Subtraction of x and y:
 [[-4 -4]
 [-4 -4]]
➤ Multiplication of x and y:
 [[ 5 12]
 [21 32]]
➤ Division of x by y:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
➤ Power x^y:
 [[    1    64]
 [ 2187 65536]]
➤ Modulus of x % y:
 [[1 2]
 [3 4]]

➤ Exponential of x (e^x):
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
➤ Natural log of x (ln x):
 [[0.         0.69314718]
 [1.09861229 1.38629436]]
➤ Base-10 log of x:
 [[0.         0.30103   ]
 [0.47712125 0.60205999]]
➤ Base-2 log of x:
 [[0.        1.       ]
 [1.5849625 2.       ]]
➤ Exponential minus 1 of x (e^x - 1):
 [[ 1.71828183  6.3890561 ]
 [19.08553692 53.59815003]]

➤ Sine of x:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
➤ Cosine of x:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
➤ Tangent of x:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]
➤ Arcsine of x (clipped):
 [[1.57079633 1.57079633]
 [1.57079633 1.57079633]]
➤ Arccosine of x (cli

You are a data engineer at a renewable-energy company that runs 3 solar farms.

Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)

Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.



In [ ]:
import numpy as np

farmA = np.array([
    [5.2, 6.3, 5.8],
    [6.0, 5.5, 6.1],
    [5.8, 6.0, 5.9],
    [6.2, 5.9, 6.0]
])

farmB = np.array([
    [4.5, 5.0, 4.8],
    [5.1, 4.9, 5.0],
    [4.8, 5.2, 4.9],
    [5.0, 5.1, 4.7]
])

farmC = np.array([
    [6.1, 6.3, 6.0],
    [6.0, 6.2, 6.1],
    [5.9, 6.0, 6.2],
    [6.2, 6.1, 6.3]
])

production_all = np.array([farmA, farmB, farmC])

print("Production array shape:", production_all.shape)
print("Size:", production_all.size)
print("Data type:", production_all.dtype)
print("Number of dimensions:", production_all.ndim)

total_per_farm = np.sum(production_all, axis=(1,2))
mean_per_farm = np.mean(production_all, axis=(1,2))
std_per_farm = np.std(production_all, axis=(1,2))
var_per_farm = np.var(production_all, axis=(1,2))

print("\nTotal energy per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Variance per farm:", var_per_farm)

hour_weights = np.array([0.5, 1.0, 0.75])

weighted_per_panel = np.array([np.dot(farm, hour_weights) for farm in production_all])
print("\nWeighted energy per panel (farms × panels):\n", weighted_per_panel)


production_all[1] += 0.5
print("\nProduction after Farm B calibration:\n", production_all[1])

mean_farm = np.mean(production_all, axis=(1,2), keepdims=True)
std_farm = np.std(production_all, axis=(1,2), keepdims=True)

production_norm = (production_all - mean_farm) / std_farm
print("\nNormalized production (first farm, first panel):", production_norm[0,0,:])

exp_norm = np.exp(production_norm)
expm1_norm = np.expm1(production_norm)

shift = abs(np.min(production_norm)) + 0.1  # ensures all values > 0
log_norm = np.log(production_norm + shift)
log10_norm = np.log10(production_norm + shift)
log2_norm = np.log2(production_norm + shift)

# Trigonometric
sin_norm = np.sin(production_norm)
cos_norm = np.cos(production_norm)
tan_norm = np.tan(production_norm)
# arcsin/arccos need [-1,1] clipping
clipped_norm = np.clip(production_norm, -1, 1)
arcsin_norm = np.arcsin(clipped_norm)
arccos_norm = np.arccos(clipped_norm)
arctan_norm = np.arctan(production_norm)
deg_norm = np.degrees(production_norm)
rad_norm = np.radians(production_norm)

# Rounding
round_norm = np.round(production_norm)
floor_norm = np.floor(production_norm)
ceil_norm = np.ceil(production_norm)
trunc_norm = np.trunc(production_norm)

# Comparison & logical
high_output = production_all > 20
even_hours_mask = np.array([True, False, True])  # dummy example for hour mask
# Broadcasting even_hours_mask over panels
even_hours_mask_broadcast = even_hours_mask[np.newaxis, np.newaxis, :]
logical_and_mask = np.logical_and(high_output, even_hours_mask_broadcast)
logical_or_mask = np.logical_or(high_output, even_hours_mask_broadcast)
logical_not_mask = np.logical_not(high_output)
logical_xor_mask = np.logical_xor(high_output, even_hours_mask_broadcast)

# Bitwise (example, make integer array shape match panels × hours)
alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,1,0],[0,0,1],[1,0,1],[1,0,0]],
    [[0,1,1],[1,0,1],[0,1,0],[1,1,1]]
])
bitwise_and_alerts = np.bitwise_and(alerts, 1)
bitwise_or_alerts = np.bitwise_or(alerts, 1)
bitwise_invert_alerts = np.bitwise_not(alerts)

# Arithmetic ufuncs on production_all
add_prod = np.add(production_all, 1)
sub_prod = np.subtract(production_all, 1)
mul_prod = np.multiply(production_all, 2)
div_prod = np.divide(production_all, 2)
power_prod = np.power(production_all, 2)
mod_prod = np.mod(production_all, 2)

# Aggregations on ufunc outputs
sum_exp = np.sum(exp_norm)
mean_sin = np.mean(sin_norm)

print("\nSum of exp(normalized):", sum_exp)
print("Mean of sin(normalized):", mean_sin)


panel_totals_per_farm = np.sum(production_all, axis=2)  # sum across hours → shape (3,4)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)  # True if any panel < 40

print("\nPanel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance per farm:", needs_maintenance)

overall_total = np.sum(production_all)
peak_hour_value = np.max(production_all)
# unravel index to farm, panel, hour
peak_idx = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all, axis=2)  # mean across hours per panel

print("\nOverall total energy:", overall_total)
print("Peak hour value:", peak_hour_value)
print("Produced by farm {}, panel {}, hour {}".format(*peak_idx))
print("Average energy per panel across all farms:\n", average_per_panel)

Production array shape: (3, 4, 3)
Size: 36
Data type: float64
Number of dimensions: 3

Total energy per farm: [70.7 59.  73.4]
Mean per farm: [5.89166667 4.91666667 6.11666667]
Std per farm: [0.28710722 0.186339   0.12133516]
Variance per farm: [0.08243056 0.03472222 0.01472222]

Weighted energy per panel (farms × panels):
 [[13.25  13.075 13.325 13.5  ]
 [10.85  11.2   11.275 11.125]
 [13.85  13.775 13.6   13.925]]

Production after Farm B calibration:
 [[5.  5.5 5.3]
 [5.6 5.4 5.5]
 [5.3 5.7 5.4]
 [5.5 5.6 5.2]]

Normalized production (first farm, first panel): [-2.40908838  1.4222329  -0.31927677]

Sum of exp(normalized): 54.25976936644647
Mean of sin(normalized): 0.06601576559920956

Panel totals per farm:
 [[17.3 17.6 17.7 18.1]
 [15.8 16.5 16.4 16.3]
 [18.4 18.3 18.1 18.6]]
Needs maintenance per farm: [ True  True  True]

Overall total energy: 209.1
Peak hour value: 6.3
Produced by farm 0, panel 0, hour 1
Average energy per panel across all farms:
 [[5.76666667 5.86666667 5.9    

Reshaping


In [ ]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


stacking and splitting


In [ ]:
a=np.array([1,2])
b=np.array([3,4])

#vertical stack
print(np.vstack((a,b)))

#horizontal stack
print(np.hstack((a,b)))

arr=np.array([1,2,3,4,5,6])
#split into three parts
print(np.array_split(arr,3))


[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]


Advanced Indexing

In [ ]:
#Boolean indexing
arr =np.array([1,2,3,4,5])
print(arr[arr>3])

#fancy indexing
arr = np.array([10,20,30,40])
indices = [0,2]
print(arr[indices])

[4 5]
[10 30]


Copy vs view

In [ ]:
#View Shares memory
arr=np.array([1,2,3])
view = arr.view()
view[0]=9
print(arr)

#copy does not share memory
copy = arr.copy()
copy[0]=10
print(copy)

[9 2 3]
[10  2  3]


Saving and loading

In [ ]:
#Save to a file
arr = np.array([10,20,30])
np.save('array.npy',arr)

#load from a file
loaded_arr = np.load('array.npy')
print(loaded_arr)

[10 20 30]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [ ]:
a1 = np.arange(10,51)
print("1D array:",a1)

a2 =np.random.rand(3,3)
print(a2)

#Array Attributes
print("Array Shape is: ",a2.shape)
print("Array size ",a2.size)
print("data type:",a2.dtype)

#Basic perations
a1_plus5=a1+5
print(a1_plus5)

a2_mulby2=a2*2
print(a2_mulby2)

#indexing and slicing
a5=np.arange(1,26).reshape(5,5)
print(a5)
print(a5[1,:])
print(a5[:,-1])
print(a5[0:3,0:2])

#Aggregation
rand_ints = np.random.randint(10,101,10)
print( rand_ints)
print(np.max(rand_ints))
print(np.min(rand_ints))
print(np.mean(rand_ints))
print(np.std(rand_ints))

#Reshaping
a3=np.arange(1,13).reshape(3,4)
print(a3)

#Broadcasting
a4=np.ones((3,3))
a5=np.array([1,2,3])
print(a4+a5)


# Filtering
rand = np.random.randint(1, 51,20)
print("Random array:", rand)
print("Elements divisible by 5:", rand[rand % 5 == 0])

#Matrix multiplication
matA = np.array([[1,2],[3,4]])
matB = np.array([[5,6],[7,8]])
mat_mult = np.matmul(matA, matB)
print( mat_mult)

#Advance Indexing
arr4x4 = np.arange(1,17).reshape(4,4)
diagonal = arr4x4[np.arange(4), np.arange(4)]
print("\n4x4 array:\n", arr4x4)
print("Diagonal elements:", diagonal)




1D array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.70320435 0.97065013 0.19340696]
 [0.20287409 0.13367151 0.08131009]
 [0.56391681 0.49624257 0.61979043]]
Array Shape is:  (3, 3)
Array size  9
data type: float64
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[1.4064087  1.94130026 0.38681392]
 [0.40574818 0.26734303 0.16262018]
 [1.12783361 0.99248514 1.23958087]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 6  7  8  9 10]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]
[11 78 93 15 15 26 23 34 79 75]
93
11
44.9
30.611925780649607
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
Random array: [35 25 40 43  2 22 28  9 46 40 44  4  6  2 38 49  5 10 40  7]
Elements divisible by 5: [35 25 40 40  5 10 40]
[[19 22]
 [43 50]]

4x4 array:
 [[ 1  2  

# **PANDAS**